environment:
  matrix:
  - TARGET: x86_64-pc-windows-msvc
    VERSION: nightly
  # - TARGET: i686-pc-windows-msvc
  #   VERSION: nightly
  # - TARGET: x86_64-pc-windows-gnu
  #   VERSION: nightly
  # - TARGET: i686-pc-windows-gnu
  #   VERSION: 1.10.0
install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-${env:VERSION}-${env:TARGET}.exe" -FileName "rust-nightly.exe"
  - ps: .\rust-nightly.exe /VERYSILENT /NORESTART /DIR="C:\rust" | Out-Null
  - ps: $env:PATH="$env:PATH;C:\rust\bin"
  - rustc -vV
  - cargo -vV

build: off

test_script:
  - set RUST_BACKTRACE=1
  - cargo test
  - cargo run
